code-name: 'redrock3'

name: "Spiky Desert Rock"
lore-blurb: "Pointed!"

health: 1100
Level: 4


#read as x, y, width and height, where x and y are the distances inside the sprite
size: [256, 128]
hitbox: [10, 10, 30, 30]
